IFIX-1010 : project update api with unit test case, code coverage,sonar fixes, changelog
misdwss/iFix-Dev pull request #85
Opened 2022-05-04 12:09 UTC by pintu-eGov

2022-05-04 18:08 UTC, rushang7-eGov requested changes

2022-05-04 18:08 UTC, rushang7-eGov commented on reference-adapter/adapter-master-data-service/src/main/java/org/egov/service/ProjectEnrichmentService.java
> +    public Project enrichUpdateProjectData(ProjectRequest projectRequest) {
Can you reuse the enrich create code? Create a new method that contains the common code.

2022-05-04 18:08 UTC, rushang7-eGov commented on reference-adapter/adapter-master-data-service/src/main/java/org/egov/validator/ProjectValidator.java
> +    public void validateProjectUpdateRequest(ProjectRequest projectRequest) {
Write common code for update and create validations in a new method.

2022-05-05 04:48 UTC, rushang7-eGov approved these changes

2022-05-05 05:02 UTC, sathishp-eGov approved these changes

2022-05-05 05:03 UTC, merged